import type { EntityConfig } from './index';

export const llpConfig: EntityConfig = {
  entityType: 'llp',
  label: 'Limited Liability Partnership',
  itrForm: 'ITR-5',
  taxAuditForm: '3CB',
  nav: {
    journal: true, cashBook: true, pettyCash: true,
    purchaseRegister: 'conditional', salesRegister: 'conditional',
    purchaseReturns: 'conditional', salesReturns: 'conditional',
    billsReceivable: true, billsPayable: true,
    ledger: true, debtors: false, creditors: false, fixedAssets: false,
    investments: 'conditional', loans: 'conditional',
    trialBalance: true, tradingAccount: 'conditional',
    profitLoss: true, profitLossFormat: 'traditional',
    plAppropriation: true, balanceSheet: true, balanceSheetFormat: 'traditional',
    cashFlowStatement: 'conditional', fundsFlowStatement: 'never',
    incomeExpenditure: false, receiptsPayments: false,
    partnersCapital: true, revaluation: true, realisation: true,
    shareCapital: false, debentures: 'never', kartaCapital: false,
    fundAccounts: false, incompleteRecords: false, memberRegister: false,
    gst: 'conditional', incomeTax: true, tdsRegister: 'conditional',
    tcsRegister: 'conditional', advanceTax: true, deferredTax: false,
    brs: true, depreciation: false,
    audit: 'conditional', auditForm: '3CB',
    inventory: 'conditional', payroll: 'never',
    segmentReporting: false, relatedParty: false, relatedPartyByLevel: true,
    accountingPolicies: false, accountingPoliciesByLevel: true,
    asChecklist: false, asChecklistByLevel: true,
    fcra: 'never', applicationCheck: false, form10b: false, llpForms: true,
    ratioAnalysis: true, bsNotes: true, taxComputation: true, msmeDisclosure: true,
    contingentLiabilities: true, directorsReport: false, caro: false, costRecords: 'never', formN: false,
    salesInvoice: true, purchaseVoucher: true, paymentVoucher: true,
    receiptVoucher: true, debitNote: true, creditNote: true,
    bankImport: true,
  },
};
